api_version: 1
runtime: python27
threadsafe: true
instance_class: F4
automatic_scaling:
  max_concurrent_requests: 25

libraries:
- name: ssl
  version: latest

handlers:
- url: /static
  static_dir: static
- url: /.*
  script: main.app
